name: Deploy to EC2

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Stack to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git pull https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_REPO }}.git main
            docker compose down
            docker compose up -d --build
            docker restart assbep-caddy
            docker image prune -f
            echo "✅ Deployment completed!"
            docker compose ps
